export const projects = [
  {
    title: "Braden's Pricing Tool",
    description: "React app created to instantly calculate a retail price for a product. This app is still under development for additional features and UI.",
      image: '/images/bradenssoc.jpg',
      tags: ['React', 'JavaScript'],
    source: 'https://bradens-soc.netlify.app/',
    visit: 'https://github.com/zpuckettdesign/bradens-soc',
    id: 0,
  },
  {
    title: 'YayNayz',
    description:"Yaynayz is a useful polling/voting app for finding out quickly if people agree or disagree. I created models and seeds for this project.",
    image: '/images/yaynayz.jpg',
    tags: ['JavaScript', 'MySQL 2', 'Bootstrap', 'Bcrypt', 'Express'],
    source: 'http://www.yaynayz.com/',
    visit: 'https://github.com/zpuckett/yaynayz',
    id: 1,
  },
  {
    title: 'Note Taker',
    description: "This app is design for a simple work space to keep track of notes. Created from Express.js.",
      image: '/images/noteexpresswt.gif',
      tags: ['Node.js', 'Express.js', 'JavaScript'],
    source: 'https://github.com/zpuckett/express-note-taker',
    visit: 'https://github.com/zpuckett/express-note-taker',
    id: 2,
  },
  {
    title: 'Weather Dashboard',
    description: "Weather-Dashboard is an application to find the current weather condition of a selected city both the current and 5-Days forecast at the same time. A server-side API was used to pull data objects for components.",
    image: '/images/weatherdash.jpg',
    tags: ['JavaScript', 'API'],
    source: 'https://weatherdashboardzp.netlify.app/',
    visit: 'https://github.com/zpuckett/weather-dashboard',
    id: 3,
  },
];
